export const levelOne = {
  mapBlueprint: [
    ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
    ['X', 'X', 1, 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
    ['X', 'X', 2, 'P', 6, 7, 8, 9, 'X', 'X'],
    ['X', 'X', 3, 4, 5, 'X', 'X', 10, 'X', 'X'],
    ['X', 'X', 'P', 'X', 'P', 'X', 'X', 11, 'X', 'X'],
    ['X', 'X', 'P', 20, 19, 18, 'P', 12, 'X', 'X'],
    ['X', 'X', 'P', 21, 'P', 17, 'X', 13, 'X', 'X'],
    ['X', 'X', 'P', 22, 23, 16, 15, 14, 'X', 'X'],
    ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
    ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
  ],
  enemyBlueprint: {
    2: 'basic',
    4: 'basic',
    6: 'basic',
    8: 'basic',
    10: 'basic',
    12: 'basic',
    14: 'basic',
    16: 'basic',
    18: 'basic',
    20: 'basic',
    22: 'basic',
    24: 'basic',
    26: 'basic',
    28: 'basic',
    30: 'basic',
    32: 'basic',
    34: 'basic',
    36: 'basic',
    38: 'basic',
    40: 'basic',
  },
  goldStart: 200,
};

export const levelTwo = {
  mapBlueprint: [
    ['X', 'X', 'X', 'X', 'X', 'X', 'X', 1, 'X', 'X'],
    ['X', 'P', 'P', 10, 9, 8, 'P', 2, 'X', 'X'],
    ['X', 'P', 'P', 11, 'X', 7, 'X', 3, 'P', 'X'],
    ['X', 'X','P', 12, 'P', 6, 5, 4, 'X', 'X'],
    ['X', 'X', 14, 13, 'P', 'X', 'P', 'P', 'P', 'X'],
    ['X', 'P', 15, 'X', 19, 20, 21, 'X', 'P', 'X'],
    ['X', 'X', 16, 17, 18, 'X', 22, 23, 'P', 'X'],
    ['X', 'X', 'X', 'P', 'X', 'X', 'X', 24, 25, 'X'],
    ['X', 'X', 'P', 'P', 30, 29, 28, 27, 26, 'X'],
    ['X', 'X', 'X', 'X', 31, 'X', 'X', 'X', 'X', 'X'],
  ],
  enemyBlueprint: {
    6: 'basic',
    8: 'basic',
    10: 'basic',
    12: 'basic',
    14: 'basic',
    20: 'basic',
    22: 'basic',
    24: 'basic',
    26: 'basic',
    28: 'basic',
    34: 'basic',
    36: 'basic',
    38: 'basic',
    40: 'basic',
    42: 'basic',
    46: 'basic',
    47: 'basic',
    48: 'basic',
    49: 'basic',
    50: 'basic',
    52: 'basic',
    55: 'basic',
    59: 'basic',
    64: 'basic',
    70: 'basic',

  },
  goldStart: 270,
};
