export const levelOne = {
  mapBlueprint: [
    ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
    ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
    ['X', 'X', 1, 'X', 'P', 'P', 'P', 'P', 'X', 'X'],
    ['X', 'X', 2, 'P', 10, 11, 12, 13, 'X', 'X'],
    ['X', 'X', 3, 'X', 9, 8, 'P', 14, 'X', 'X'],
    ['X', 'X', 4, 5, 6, 7, 'P', 15, 'X', 'X'],
    ['X', 'X', 'X', 'P', 'P', 'P', 'X', 16, 'X', 'X'],
    ['X', 'X', 22, 21, 20, 19, 18, 17, 'X', 'X'],
    ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
    ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
  ],
  enemyBlueprint: {
    1: 'jesus',
    2: 'jesus',
    4: 'jesus',
    5: 'jesus',
    7: 'basic',
    8: 'basic',
    9: 'basic',
    10: 'basic',
    11: 'basic',
    13: 'basic',
    14: 'basic',
    16: 'basic',
    19: 'basic',
    21: 'basic',
    22: 'basic',
    25: 'jesus',
    26: 'basic',
    27: 'jesus',
    30: 'basic',
    31: 'basic',
    32: 'basic',
    34: 'basic',
    37: 'basic',
    39: 'basic',
    41: 'basic',
    42: 'basic',
    43: 'basic',
    45: 'basic',
    50: 'basic',
    53: 'basic',
    55: 'basic',
    61: 'basic',
    63: 'basic',
    71: 'basic',
    80: 'basic',
    90: 'jesus',
    100: 'basic',
    110: 'basic',
    120: 'jesus',
    130: 'jesus',
  },
  goldStart: 190,
  allowedTowers: [
    'cross',
    'vertical',
    'horizontal',
    'surround',
    'array',
  ],
};

export const levelTwo = {
  mapBlueprint: [
    ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
    ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
    ['X', 'X', 22, 'P', 'X', 'X', 'X', 1, 'X', 'X'],
    ['X', 'X', 21, 'P', 'P', 'P', 3, 2, 'X', 'X'],
    ['X', 'X', 20, 19, 18, 'P', 4, 'P', 'X', 'X'],
    ['X', 'X', 'P', 'P', 17, 'X', 5, 6, 'X', 'X'],
    ['X', 'X', 14, 15, 16, 'P', 'P', 7, 'X', 'X'],
    ['X', 'X', 13, 12, 11, 10, 9, 8, 'X', 'X'],
    ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
    ['X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'],
  ],
  enemyBlueprint: {
    2: 'tall',
    4: 'tall',
    6: 'tall',
    8: 'tall',
    10: 'basic',
    11: 'basic',
    12: 'basic',
    14: 'basic',
    15: 'basic',
    16: 'basic',
    18: 'basic',
    20: 'basic',
    22: 'basic',
    25: 'basic',
    27: 'basic',
    30: 'basic',
    32: 'basic',
    35: 'basic',
    37: 'basic',
    40: 'basic',
    43: 'basic',
    47: 'basic',
    50: 'tall',
    53: 'tall',
    57: 'tall',
    60: 'tall',
    65: 'basic',
    70: 'basic',
    75: 'basic',
    80: 'basic',
    85: 'basic',
    90: 'basic',
    100: 'basic',
    110: 'tall',
    120: 'tall',
    135: 'tall',
    150: 'tall',
  },
  goldStart: 180,
  allowedTowers: [
    'cross',
    'vertical',
    'horizontal',
    'surround',
    'column',
  ],
};

export const levelThree = {
  mapBlueprint: [
    ['P', 'P', 'P', 'P', 1, 'X', 'X', 'X', 'X', 'X'],
    ['P', 'P', 'P', 'P', 2, 'X', 16, 17, 18, 'X'],
    ['P', 'P', 5, 4, 3, 'X', 15, 'P', 19, 'X'],
    ['P', 'P', 6, 'X', 'P', 'P', 14, 'P', 20, 'X'],
    ['X', 'X', 7, 'P', 'P', 'P', 13, 'P', 21, 'P'],
    ['X', 'X', 8, 9, 10, 11, 12, 'X', 22, 'P'],
    ['X', 'X', 'P', 'P', 'P', 'P', 'X', 'P', 23, 'P'],
    ['X', 'X', 'X', 'X', 'X', 27, 26, 25, 24, 'P'],
    ['X', 'X', 'X', 'X', 'X', 28, 'P', 'P', 'P', 'P'],
    ['X', 'X', 'X', 'X', 'X', 29, 'P', 'X', 'X', 'X'],
  ],
  enemyBlueprint: {
    1: 'basic',
    2: 'basic',
    3: 'basic',
    4: 'basic',
    5: 'basic',
    6: 'basic',
    7: 'basic',
    8: 'basic',
    9: 'basic',
    10: 'basic',
    11: 'basic',
    12: 'basic',
    13: 'basic',
    18: 'advanced',
    20: 'basic',
    21: 'basic',
    22: 'basic',
    23: 'basic',
    24: 'basic',
    25: 'basic',
    26: 'basic',
    27: 'basic',
    28: 'basic',
    29: 'basic',
    30: 'basic',
    35: 'jesus',
    37: 'jesus',
    40: 'jesus',
    45: 'basic',
    46: 'basic',
    47: 'basic',
    48: 'basic',
    49: 'basic',
    50: 'basic',
    55: 'long',
    56: 'long',
    57: 'long',
    70: 'basic',
    71: 'basic',
    72: 'basic',
    75: 'basic',
    81: 'basic',
    82: 'basic',
    83: 'basic',
    90: 'advanced',
    100: 'advanced',
    105: 'jesus',
    106: 'jesus',
    107: 'jesus',
    108: 'jesus',
    120: 'long',
    121: 'long',
    122: 'long',
    123: 'long',
  },
  goldStart: 245,
  allowedTowers: [
    'cross',
    'vertical',
    'horizontal',
    'surround',
    'array',
    'column',
  ],
};

export default {
  levels: [
    levelOne,
    levelTwo,
    levelThree,
  ],
}
